app:
  greeting: "Hello"

server:
  port: 8080
  host: 0.0.0.0

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://127.0.0.1:54321/vmcs"
    username: "vmcs"
    password: "vmcs"
  statements:
    select-all: "SELECT * FROM drinks"